// @ts-check

import esbuild from "esbuild";
import sveltePlugin from "esbuild-svelte";
import process from "process";
import { builtinModules } from "module";

const production = process.argv[2] === "production";
const banner = `/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */`;

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts", "src/styles.css"],
  outdir: ".",
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  loader: {
    ".png": "dataurl",
  },
  minify: production,
  plugins: [
    sveltePlugin({
      compilerOptions: { css: "injected" },
    }),
  ],
});

if (production) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
