// @ts-check

import esbuild from "esbuild";
import sveltePlugin from "esbuild-svelte";
import process from "node:process";
import { builtinModules } from "node:module";
import { sveltePreprocess } from "svelte-preprocess";

const isProdBuild = process.argv[2] === "production";
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts", "src/styles.css"],
  outdir: ".",
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  define: { __DEV__: String(!isProdBuild) },
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: isProdBuild ? false : "inline",
  treeShaking: true,
  loader: {
    ".png": "dataurl",
  },
  minify: isProdBuild,
  plugins: [
    sveltePlugin({
      compilerOptions: { css: "injected" },
      preprocess: sveltePreprocess(),
    }),
  ],
});

if (isProdBuild) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
